# Увеличенная память для Gradle Daemon
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
android.overridePathCheck=true

# Параллельная сборка
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Android
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
